name: argon2_flutter_web
description: A web implementation of the PHC winner Argon2 to be used on Web Projects
version: 0.1.2
homepage: https://github.com/Paradoxu/argon2-flutter/argon2_flutter
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  argon2_flutter_interface:
    git:
      url: https://github.com/Paradoxu/argon2-flutter.git
      path: argon2_flutter_interface
      
  flutter:
    sdk: flutter
  js: ^0.6.3

flutter:
  plugin:
    platforms:
      web:
        pluginClass: Argon2FlutterWeb
        fileName: argon2_flutter_web.dart

  assets:
    - assets/argon2.wasm
    - assets/argon2-module.js
    - assets/argon2-utils.js
